### ISSUE TITLE
Apply image restoration sequentially before segmentation

### ISSUE THREAD

**Issue by Feanor007** [MouseLand/cellpose#1047]
Hi Cellpose Team, 

Great work! I am wondering if Cellpose3 supports applying denoising/deblurring/upsampling in a sequential manner before the final segmentation layer. For example, I want to denoise and deblur the image before segmentation. From the document provided, I couldn't find if this is possible.

**Comment by ashishUthama** [comment]
If you can invoke cellpose from Python, you could do this using the '[DenoiseModel](https://cellpose.readthedocs.io/en/latest/restore.html)'

Instantiate the model you want and apply the restoration sequentially, and then call the CellposeModel to segment.

**Comment by derekthirstrup** [comment]
@Feanor007 @carsen-stringer I implemented a denoising script to process a folder of 3D image stacks since I found errors in the way rescaling in done within cellpose.  This script also does not tile the image which leads to intensity scaling artifacts in out of focus planes with tiled denoising as implemented in cellpose. The camera pixel offset has to be subtracted before min/max or percentile rescaling and this is not done properly with current cellpose rescaling method.  Camera pixel offset subtraction (no px binning images =100)  works great although it is ideal to use a per pixel black reference subtraction. Often it is not necessary unless you have camera with a lot of fixed pattern noise.  You can probably leverage this script for your own purpose.  https://github.com/AllenCell/EMT_image_analysis/blob/bioRxiv-v1/H2B_and_EOMES_instance_segmentation/1_CP3DenoiseModel_RescalePerTimepoint.py

**Comment by Feanor007** [comment]
> @Feanor007 @carsen-stringer I implemented a denoising script to process a folder of 3D image stacks since I found errors in the way rescaling in done within cellpose. This script also does not tile the image which leads to intensity scaling artifacts in out of focus planes with tiled denoising as implemented in cellpose. The camera pixel offset has to be subtracted before min/max or percentile rescaling and this is not done properly with current cellpose rescaling method. Camera pixel offset subtraction (no px binning images =100) works great although it is ideal to use a per pixel black reference subtraction. Often it is not necessary unless you have camera with a lot of fixed pattern noise. You can probably leverage this script for your own purpose. https://github.com/AllenCell/EMT_image_analysis/blob/bioRxiv-v1/H2B_and_EOMES_instance_segmentation/1_CP3DenoiseModel_RescalePerTimepoint.py

Thanks for sharing! I will take a look.

**Comment by derekthirstrup** [comment]
This script also generates an output csv that is a record of the rescaling values for each timepoint.  The other script in that repo uses a file put in the output folder named "input_scale_values.csv" which applies a constant rescaling ratio for all images which maintains the intensity relationship to the raw data over time which is important for proteins that change expression level during the timelapse.  https://github.com/AllenCell/EMT_image_analysis/blob/bioRxiv-v1/H2B_and_EOMES_instance_segmentation/1_CP3DenoiseModel_ScaleValuesFromCSV_ConstantScalingOutput.py
