### ISSUE TITLE
Distribution and versioning of models

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#114]
Long term, it might be worth considering a way to distribute models more cleanly and in a version controlled manner.  When I tried to start a cluster which was using cellpose, all the machines simultaneously tried to download the model files and the http server failed.  This caused the cluster to crash.  In addition, having models outside of version control could lead to reproducibility issues down the line.

As a workaround, we store the model files directly in a branch of our github cellpose fork.  They are small enough this is not a problem, but I don't think it's a great long term solution.  There are likely some good solutions for this, but I don't know the space very well.

FYI, here is the commit that adds the files and updates the code to use them (I have not tested the GUI):
https://github.com/deisseroth-lab/cellpose/commit/cbce0b4339e9d2fb1a0a96eaf74e60970a74a0fc

**Comment by chrisroat** [comment]
Sorry, but the commit changed.  It's https://github.com/deisseroth-lab/cellpose/commit/dcbcefadd342cb721cacde48350e3fb04fd36062

**Comment by chrisroat** [comment]
Would you all be open to storing the model files are part this github repo / pypi package, perhaps after you stop supporting mxnet?

**Comment by carsen-stringer** [comment]
I will not overwrite the https paths so there will always be the original versions. I agree this is not ideal, but dealing with something like dvc is also annoying and I don't want users to have to do that. 

Can you copy the model files to your `.cellpose` folder on the server so that the download doesn't trigger?

**Comment by chrisroat** [comment]
I think if the models do start getting versioned, version control is something people may be forced to get used to.  I've always found git annoying, but here we are having a discussion on github.  :)

But to your point... yes, we could build our docker files with the .cellpose folder pre-installed, so there would be some tracking of versions.   I'd still check in the model files to some repository for doing that build, so we can maintain the versions ourselves somewhere.

For now, we just maintain a fork of cellpose with a branch where we include the models inside the package (see the commit above).  I haven't updated yet to the pytorch update -- it looks like the model loading is more streamlined now, so the required code changes will be fewer.

**Comment by arogozhnikov** [comment]
Hi @carsen-stringer,
I see the issue is closed, but can you please describe current policy on versioning?

For example: is cellpose==1.0.2 expected to download the same models or will it download new models after cellpose==2.* is release?

We'd like to be able to compare results from multiple experiments by using the same segmentation (and experiments are quite separated in time), so it is important to track an actual version used
