### ISSUE TITLE
Segmentation of Nuclear Substructures

### ISSUE THREAD

**Issue by H2AX** [MouseLand/cellpose#14]
Dear Mouseland,

We seek a way to reliably segment/mask so-called nucleoli in DIC microscopy pictures.
These are the convex substructures within the nuclei that you can see in the attached sample image. Ideally these masks could then be imported into the ROI Manager of Fiji/ImageJ for further analysis. So far it was all performed by hand using a wacom tablet and a pen. Could this be implemented in cellpose? How can we contribute to make this happen?
![segmentation_test](https://user-images.githubusercontent.com/60927585/74241089-99cb2e80-4cdb-11ea-8375-d2b0b8a0ce09.jpg)

**Comment by marius10p** [comment]
This looks doable to me. A few thoughts:

1) we wouldn't want to incorporate these images into the main "generalist" cellpose, because it would get confused between segmenting nuclei and nucleoli.

2) we could train a separate model just for nucleoli (it could be initialized with the generalist model). This would need at least 10 manually segmented images like the one you just posted. You can use the GUI to do the segmentation, make sure the npy file gets saved next to the original images. You should be able to reload that into the GUI to make sure it got saved. 

If you choose 2), we'd be happy to train the model, provided you agree to include it as an optional public model that other users can download. In the medium term, we will also release notebooks and information to help users train their own models.

**Comment by H2AX** [comment]
Wow, i didn't expect such a quick reply! So, to understand this correctly, i would segment 10+ sample images in the GUI of cellpose, then 'save as .npy' and submit the files to you? How? Can i attache e.g. a zip archive to one of my replies? (Sorry, i was never on GitHub before). Of course everyone shall be able to use the resulting model!

**Comment by marius10p** [comment]
If you use the automated "send to server button" from the GUI, we should be able to pick them up. Just let us know when you're done. If that fails somehow, you can also just send the local npy files for each image. Might be best to segment one image first and post it here so we can advise if any modifications are needed.

**Comment by H2AX** [comment]
So, i just segmented one picture manually and submitted to your server. Here's what it looks like on my screen:

![Test_Images_1](https://user-images.githubusercontent.com/60927585/74248439-dc930380-4ce7-11ea-9001-295f1e8545a3.jpg)
<img width="697" alt="Test_Mask_1" src="https://user-images.githubusercontent.com/60927585/74248449-e0bf2100-4ce7-11ea-8ae5-40beec774e27.png">

Please let me know if there is anything that i should improve. Also, false positives are to be avoided at the cost of false negatives; we will simply calculate a ratio based on the signal in the other channels within those ROIs.

**Comment by marius10p** [comment]
Thanks. Are you missing some of them here though, like in the nucleus below? It is important to train on dense segmentations, otherwise the algorithm will learn that it's ok to miss some nucleoli. 

![image](https://user-images.githubusercontent.com/3935246/74255145-74302c00-4cbf-11ea-888a-7ed3a32f6334.png)

**Comment by H2AX** [comment]
From experience, we know that the relevant nucleoli are rather big and of round shape. The cells which you are referring to would've been excluded in a manual count. It doesn't matter if we miss some positives, als long as there are no false negatives in the segmentation.

**Comment by marius10p** [comment]
Sounds good. As a rule of thumb, any biases, intended or not intended, that you put into the training set will also show up in the model.

**Comment by H2AX** [comment]
Hi Marius10p,

Meanwhile, i've sent 20 manually segmented pictures to your server. Did they reach you? Can you (re-)train your model with them?

**Comment by pskeshu** [comment]
is it possible to retrain the model ourselves locally?

**Comment by carsen-stringer** [comment]
hey both sorry for the delay we recommend trying out the latest cellpose version (`pip install cellpose --upgrade`) which enables local training in the gui with the `_seg.npy` files you've created
