### ISSUE TITLE
TORCH CUDA version not installed/working

### ISSUE THREAD

**Issue by papalagirauscher** [MouseLand/cellpose#203]
Hello,
I updated to the new cellpose version, but keep receiving 

TORCH CUDA version not installed/working

tried different cuda toolkits (9, 10.1, 10.2), my gpu supports until 10.2
Nvidia -smi shows driver version 440.33.01, highest possible CUDA 10.2
Nvcc -V shows coda compilation tool v. 10.1 (but i think pytorch uses its own library and not the system one?)

Any ideas?

Thank you,
Jan

**Comment by quentin67100** [comment]
I just wanted to post an issue about this ! 
I work on an HPC servers. The CPU works wells, but for the gpu i obtained the same error "TORCH CUDA version not installed/working" and i don't understand why. I use cellpose wth a conda env in our HPC servers, and we have a GPU node in our severs. When i do the commande line nvidia-smi i obtained this result  l don't put all because it's too long) : 
NVIDIA-SMI 418.39 Driver Version: 418.39 CUDA Version: 10.1 | |-------------------------------+----------------------+----------------------+ | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. | |===============================+======================+======================| | 0 Tesla K80 On | 00000000:06:00.0 Off | 0 | | N/A 26C P8 26W / 149W | 0MiB / 11441MiB | 0% Default | +-------------------------------+----------------------+----------------------+ | 1 Tesla K80 On | 00000000:07:00.0 Off | 0 | | N/A 31C P8 28W / 149W | 0MiB / 11441MiB | 0% Default |

**Comment by quentin67100** [comment]
Finally for me it's work with cudatoolkit=10.1

**Comment by romainGuiet** [comment]
Hi @papalagirauscher ,

I had the same issue before and I solved it by enforcing pytorch from pytorch channel , see below in yml file
```
dependencies:
  - python>3.4,<3.8
  - pip
  - pyqt
  - cudnn==7.6.0
  - cudatoolkit=10.1
  - pytorch::pytorch 
```
and you can find in the documentation another way of doing it: 
``` conda install pytorch cudatoolkit=10.1 -c pytorch ```

I hope it solves your issue,

Best,

Romain

**Comment by carsen-stringer** [comment]
thanks for the help @romainGuiet
