### ISSUE TITLE
Precision-recall curves

### ISSUE THREAD

**Issue by Wouter2021** [MouseLand/cellpose#238]
Dear community,

I would like to extract Precision-Recall curves from CellPose (or do this externally with a script of my own) in order to compare my results to earlier works, but I am having difficulty in doing so. I do not see any direct way to do this within CellPose currently, and to do it with a self-written script, I believe that I would need to use a score per mask. That is, not a score per pixel within a mask (like the cell probability score), but per full mask, in order to calculate based on a varying threshold value for the mask score, a different precision and recall value.

If I am correct, the model match threshold/score (see GUI, in the scripts referred to as flows threshold/score) is related to what I would need for this.

Ideally, I would extract a single score per full mask from CellPose, in order to do my own calculations with it. Does anyone have ideas on how to extract this? The _seg.npy file only contains pixel-level scores (cell probability), not full mask-level scores (as far as I could find).

The flows threshold is passed from the __main__ to models.CellPoseModel.eval, to dynamics.get_masks and dynamics.bad_flow_masks. But I am not managing to figure out how to rewrite the script there in order to extract the flow scores per mask.

Are there any people who already did this and are willing to share their scripts? Or that have a script to calculate the Precision-Recall curves within CellPose or have ideas on how to do this?

All help is appreciated. Thanks in advance.

**Comment by kevinjohncutler** [comment]
I think @carsen-stringer might have scripts to share that were used to do the quantitative comparisons in the paper - that what I understand from your comment about 'earlier works'. But otherwise it sounds like you are really just probing the cellpose output itself. You could do this by first running the labels_to_flows function on the cellpose output, and then loop over all the predicted labels and do a mean-square-error comparison of the generated flow to the predicted flow (for just that label region). Almost exactly this is implemented within cellpose already with the additional functionality of throwing out regions with a MSE that is too high. So you could adapt that code and save the MSE per mask as it goes along. But maybe you already did all this, it has been a couple weeks since you posted!

**Comment by carsen-stringer** [comment]
indeed we have several metrics functions here: https://github.com/MouseLand/cellpose/blob/master/cellpose/metrics.py

I'm guessing you have the ground-truth labels for your images, in which case you use those as `masks_true` and the cellpose masks as `masks_pred`
