### ISSUE TITLE
stitch_threshold, correct input/output

### ISSUE THREAD

**Issue by timblosser** [MouseLand/cellpose#304]
When using stitch_threshold, what is the correct input and the expected output? I have tried providing an image stack ( (z,x,y) array) and the corresponding output mask has only two dimensions (x,y) - I was expecting to have mask information for each z-plane. Is this correct? The documentation on this is a bit vague.

**Comment by puisheelee** [comment]
Hi, 

I got stitch_threshold working properly, by organizing the image stack into a folder containing all .tif files of each having a single z-plane (i.e. if your image stack has z = 100, then the folder contains 100 single xy images in chronological order). The output would be a single .npy and .tif with the correct dimension. 

Hope this helps!

**Comment by timblosser** [comment]
Thanks for the tip. I got it working as well using a list of images (each z-plane as each item) rather than a 3-D numpy array.

**Comment by carsen-stringer** [comment]
I think this should be working with a stack now if you specify "z_axis=0" for example for a Z x X x Y tiff, otherwise it may assume that Z is channels, please try the latest version though, `pip install git+https://github.com/mouseland/cellpose.git`

going to close for now but please let me know if it's still not working
