### ISSUE TITLE
Is there a way to quickly know how many cells are segmented by using command line ? 

### ISSUE THREAD

**Issue by troygarry** [MouseLand/cellpose#315]
Hi everyone, 

First of all, please allow me to say thank you to these authors, brilliant tools super useful. 
When I use the GUI version of cellpose, the terminal always return how many cell were found. My question is how to quickly get this info after using the command line to analyze a folder of images? the output files are usually  .npy, png and a text file for imageJ ROI manager. I could use the ROI manage, but just wondering if there is a simpler way to do so. 

thanks in advance, 
Troy

**Comment by Erwan67** [comment]
hi @troygarry 

yes it's possible !
1- Save the outlines for fiji 
![outline](https://user-images.githubusercontent.com/51329059/131460720-d7075f63-dec2-430f-be98-8957c9560e46.JPG)
2- Then reopen it and count the number of rows because each row equals one ROI. In my "code" I create a *.txt file and I put the name of the initial image and the Roi number.
![roi](https://user-images.githubusercontent.com/51329059/131461248-16cc8f91-a518-4761-86a1-7daefd4947ef.JPG)

**Comment by carsen-stringer** [comment]
thanks @Erwan67 !

**Comment by 2809654608** [comment]
> me to say thank you to these authors, brilliant tools super useful.
> When I use the GUI version

Hello, do you need to create these scripts by yourself? Or are they part of the original file (Cellpose provide)?
