### ISSUE TITLE
Omnipose??

### ISSUE THREAD

**Issue by mrseekdeep** [MouseLand/cellpose#363]
@kevinjohncutler Hello,
just noticed that you've posted omnipose with some sort of CC licence.
is there a reason for not choosing BSD 3-Clause

**Comment by kevinjohncutler** [comment]
Hi @mrseekdeep, the reason is that my lab/university wanted to release it with a more restrictive license (AGPL3, similar to the GPL3 license that SuperSegger is released under - a tool released some years ago by one of the labs I am in). This should not affect any researchers, with the intent to help raise funds for my respective labs in the case that companies want to integrate Omnipose into their software. However, I honestly feel conflicted about it. I'm interested to hear more about what the community thinks.
