### ISSUE TITLE
GPU starting  problem.

### ISSUE THREAD

**Issue by arkansertan** [MouseLand/cellpose#366]
Dear All, 
I was successfully installing  and using cellpose before update on 7th of  November.   GPU have not been  opened and worked with my computer even though I follow each steps of installation.  I use  MacOS Big Sur, and visual studio code. 

Here are installation steps that I follow in my terminal of visual studio code  
1- conda create --name cellpose python=3.8
2- conda activate cellpose
3-python -m pip install cellpose[all]  or python -m pip install 'cellpose[all]'
4- python -m pip install cellpose --upgrade
5-  python -m cellpose, 

GPU does not appear in my screen. 

Could you please help me about this situation ? 

best regards,
Sertan

**Comment by kevinjohncutler** [comment]
What GPU do you have? I think only Nvidia GPUs are supported through pytorch, and no modern Nividia GPUs will work in macOS (no driver support). It is possible that a much older Nvidia card will work because the drivers exist, but I doubt that is your situation. Most likely you will only be able to use CPU on macOS, at least until pytorch supports AMD and/or Apple Silicon GPUs.

**Comment by arkansertan** [comment]
Hello Dear Kevin, 
My problem was solved ! cellpose works 
thank you so much for your comments, 
best,
Sertan
