### ISSUE TITLE
tissuenet (mesmer) training data integration?

### ISSUE THREAD

**Issue by mezwick** [MouseLand/cellpose#381]
Hi,
I wondered whether you planned to incorporate the 1 million cell annotations in the TissueNet database (recently released as part of mesmer) into the cellpose model?

Thanks!

**Comment by kevinjohncutler** [comment]
Thanks for the heads-up. From an initial look at their paper, they appear to have already trained Cellpose on TissueNet to obtain their results, so in principle we should be able to request their Cellpose model and host it as a default model for users. That said, Cellpose appears to be far inferior to Mesmer on this dataset, so it would be worth investigating why this is so (exact training settings, channels, size model, etc). I also would want to train Omnipose on the TissueNet data and see how it compares. If weird cell shapes or huge variations in cell size due to the nature of tissue slices is the point of failure, Omnipose may well make up for the performance discrepancy with Mesmer.

**Comment by carsen-stringer** [comment]
cellpose now has tissuenet models built in, please `pip install cellpose --upgrade`

we do not see that the tissuenet model mesmer outperforms cellpose in our comparisons (see paper: https://www.biorxiv.org/content/10.1101/2022.04.01.486764v1)
