### ISSUE TITLE
Error while using CPU for segmentation-  "NET ERROR: PytorchStreamReader failed reading zip archive: failed finding central directory"

### ISSUE THREAD

**Issue by sindhum98** [MouseLand/cellpose#418]
When I try segmentation using CPU, I am getting the error- "NET ERROR: PytorchStreamReader failed reading zip archive: failed finding central directory"
I can't check if it works using GPU because my graphics card compute capacity seems to be incompatible with pytorch

**Comment by kevinjohncutler** [comment]
@sindhum98 what is your GPU and OS?

**Comment by sindhum98** [comment]
Windows 10 OS, and NVIDIA GEforce GT730

**Comment by carsen-stringer** [comment]
can you try deleting your models folder and redownloading them? there may have been an interruption during download (see this issue: https://github.com/pytorch/pytorch/issues/31620)? 

the models folder is in your home directory `/.cellpose/models`, in windows e.g. `C:/Users/carsen/.cellpose` or linux e.g. `/home/carsen/.cellpose`

going to close issue for now please comment if it's still not working

**Comment by sindhum98** [comment]
Thanks! I tried that and I'm still getting the same error.

**Comment by xfd997700** [comment]
Simply deleting the directory is still difficult to solve the issue, it occurs because of the incomplete download of models, which is usually related to network conditions. In my case, I fixed the issuse by manually download the required models in https://www.cellpose.org/models/{MODEL_NAME} and put them in .cellpose\models. Also, if you encounter the issue, your .cellpose\style_choice.npy is also probably incomplete, and you can manually download it from https://www.cellpose.org/static/models/style_choice.npy, replace the incomplete files. GOOD LUCK!
