### ISSUE TITLE
--diameter flag overwritten by defaults when retraining a model

### ISSUE THREAD

**Issue by sidpanda1** [MouseLand/cellpose#452]
I am trying to train a pre-trained model on the command line, and I have been running into a few issues.

1) Whenever, I set the diameter parameter to 9.0, Cellpose automatically defaults the training to be done at 30px.  How can I get it to stop doing this?
![image](https://user-images.githubusercontent.com/88005443/155216345-c5255df6-c207-4821-bfc7-e0ae0dcd0366.png)

2) Whenever, I specify a pre-trained model, Cellpose recognizes and accesses that file while training. However, it does not modify it. At the end of training, there is a new model that is saved in the folder of images that I used for training. Is the latest model that it saves an aggregate of the previous training cycle and this current training cycle? Or, should I continue to use the previous model as the most "trained" model?

Thanks for all the help!

**Comment by kevinjohncutler** [comment]
Looking at `__main__.py`,  there is the following code:

```python
if not os.path.exists(cpmodel_path):
    if not args.train:
        error_message = 'ERROR: model path missing or incorrect - cannot train size model'
        logger.critical(error_message)
        raise ValueError(error_message)
    cpmodel_path = False
    logger.info('>>>> training from scratch')
    if args.diameter==0:
        rescale = False 
        logger.info('>>>> median diameter set to 0 => no rescaling during training')
    else:
        rescale = True
        szmean = args.diameter 
else:
    rescale = True
    args.diameter = szmean 
    logger.info('>>>> pretrained model %s is being used'%cpmodel_path)
    args.residual_on = 1
    args.style_on = 1
    args.concatenation = 0
if rescale and args.train:
    logger.info('>>>> during training rescaling images to fixed diameter of %0.1f pixels'%args.diameter)
```

You're down at the bottom `else` branch, and `args.diameter` is overwritten with `sizemean`. And `sizemean` happens to be set to `30.` not far above:

```python
else:
    if builtin_model:
        if args.mxnet and args.pretrained_model=='cyto2':
            logger.warning('cyto2 model not available in mxnet, using cyto model')
            args.pretrained_model = 'cyto'
        cpmodel_path = models.model_path(args.pretrained_model, 0, not args.mxnet)
        if cytoplasmic:
            szmean = 30.
        elif nuclear:
            szmean = 17.
        elif bacterial:
            szmean = 0. #bacterial models are not rescaled 
    else:
        cpmodel_path = os.fspath(args.pretrained_model)
        szmean = 30.
```
The intent here must be that if you are retraining a model, you are forced to use the same mean diameter as the one with which the original model was trained. This makes sense, but I also see no reason why not to allow users to play with it. And actually, the variable `szmean` clearly defaults to 30 for **any** custom pretrained model!! Ideally, custom models should act just like built-in models and 'remember' the cell size it is trained to segment (or rather, the target size for rescaling input images). So there are two changes to make:

1. Read in `szmean` from the model itself (`diam_mean` internally)
2. Make `--diameter` apply to any pretrained model

To do the latter, I think we can safely just replace the line `szmean = 30.` with `szmean=args.diameter`, because `args.diameter` defaults to 30 anyway. That will fix your problem for now.

**Comment by sidpanda1** [comment]
> The intent here must be that if you are retraining a model, you are forced to use the same mean diameter as the one with which the original model was trained. 

Hi! Thanks for your reply. I originally trained the model at 9.0 px, and I have always tested it using 9.0 px. Do you think the issue may be stemming from the fact that `szmean` is default set to 30px?

**Comment by kevinjohncutler** [comment]
@sidpanda1 yes, that's the reason. Your training assumes that images are always rescaled prior to evaluation, so you must run cellpose with a diameter of 9 in the input. This upscales the images, which I doubt gives you any better performance, so my suggestion is to just redo the training with rescaling turned off (diameter=0) and always evaluate with rescaling off. Note that you'll want to make sure that the interp option is turned on so that you reduce the integration artifacts over such small cells.

**Comment by carsen-stringer** [comment]
sorry about this, this was a poor implementation of this parameter. from now on the mean diameter used is saved with the model, and can be specified for training with the flag `--diam_mean` or in a notebook with `diam_mean` parameter in the `CellposeModel()` function. please `pip install cellpose --upgrade` and see more details here: https://cellpose.readthedocs.io/en/latest/models.html#user-trained-models
