### ISSUE TITLE
Segmentation using self trained model from python script returns different results to running from command line

### ISSUE THREAD

**Issue by miguelatienza** [MouseLand/cellpose#470]
I have trained a model from scratch (from the command line). If I run this model on a given set of images from the command line, the results are very good, however if I run the same model from a python script, the results are complete nonsense. Running the default cyto model from the python script seems to work fine.

**Comment by kevinjohncutler** [comment]
@miguelatienza could you share the code you used to train and the code you used to evaluate the model in python and CLI? One thing that comes to mind is that you might be using the `Cellpose` class instead of `CellposeModel`, the former of which uses a `SizeModel` and that could be the culprit, especially for custom models.

**Comment by carsen-stringer** [comment]
yes thanks Kevin, this could be the issue. we've added a code-based notebook to use custom models that may help you pinpoint your error: https://colab.research.google.com/github/MouseLand/cellpose/blob/main/notebooks/run_cellpose_2.ipynb 

going to close this for now but please let us know if you're still having issues
