### ISSUE TITLE
Support custom torch device 

### ISSUE THREAD

**Issue by Nelson-Gon** [MouseLand/cellpose#587]
Hi, 

Thanks for the package. From the docs, it is possibel to override `gpu` by setting `device` to something else. However, in the code, it seems the device is limited to use only `cuda`. Please see the relevant lines

https://github.com/MouseLand/cellpose/blob/62d0e0460cdce777b0b557bfcdf4c0e4e5627f9d/cellpose/core.py#L95-#L100

I would like to set this to something else e.g. `torch.device('mps')` to use a GPU on an M1 chip.

Thank you,
NelsonGon

**Comment by carsen-stringer** [comment]
You can pass any device directly into the `CellposeModel` or `Cellpose` class.

I've added an option to pass a string on the command line instead of only a number for the device type with `--gpu_device mps`

please try it with `pip install git+https://github.com/mouseland/cellpose`

it check that it can create the device but otherwise will not check if it's working
