### ISSUE TITLE
ValueError: 'minlength' must not be negative

### ISSUE THREAD

**Issue by chenzhao2016** [MouseLand/cellpose#616]
Hi there, I was running a large image via Cellpose CPU version and encountered "ValueError: 'minlength' must not be negative" 
<img width="817" alt="CellPose_negative error" src="https://user-images.githubusercontent.com/102878000/205546214-d8c6fdb8-ef8d-4efa-a6b4-c2133131111a.png">
I wonder if anyone has seen this error before. If so, any suggestions will be appreciated.

**Comment by carsen-stringer** [comment]
thanks for reporting this, is this the latest version? I thought we had fixed a bug like this. If it is please upload your image so we can test it

**Comment by carsen-stringer** [comment]
Ah I see it failed in the diameter step. I think it's due to the really large size, Cellpose can't figure out the size correctly. I'd recommend rescaling it before running cellpose, you can make it a size where the nuclei are around 30 pixels in diameter, that is default for the cyto models. And also then you can set the diameter manually and not rely on the auto-detection

**Comment by carsen-stringer** [comment]
(when I ran it in full size it never completed, at least on the GPU, the job was killed)

**Comment by chenzhao2016** [comment]
Thank you!
