### ISSUE TITLE
It takes 45min for GUI to open...

### ISSUE THREAD

**Issue by josenimo** [MouseLand/cellpose#617]
Hi,

I installed cellpose as described in issue [Issue 481](https://github.com/MouseLand/cellpose/issues/481).
`conda create -n cellpose pytorch=1.8.2 cudatoolkit=10.2 -c pytorch-lts`
`conda activate cellpose`
`pip install cellpose`

I also tried using `pip install cellpose[GUI]` instead, or adding `python=3.8` to it. But same result.

(cellpose-GPU) PS C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose-GPU\Scripts> python -m cellpose
2022-12-05 15:35:25,219 [INFO] WRITING LOG OUTPUT TO C:\Users\Administrator\.cellpose\run.log
2022-12-05 16:08:15,051 [INFO] ** TORCH CUDA version installed and working. **

A 35+min wait for the GUI to open up. Any advice?

Conda list:

[conda list.txt](https://github.com/MouseLand/cellpose/files/10155876/conda.list.txt)

**Comment by carsen-stringer** [comment]
unfortunately I think this is a really slow torch import. you can test this by running python and importing torch and creating an array on the GPU to see how long that takes. I'm not sure if you have to use such an old cudatoolkit, that could be the issue. going to close since I don't think this is cellpose specific but let me know what you think

**Comment by MoonMess** [comment]
Up! I have the same issue, did someone fand a solution to launch the GPU version of GUI?
