### ISSUE TITLE
Cellpose detects all the images of the folder twice

### ISSUE THREAD

**Issue by TAspert** [MouseLand/cellpose#626]
Cellpose detects all the images from the folder twice. They are also used twice for the training.
I think it comes from the function cellpose.io.get_image_files.
See: https://imgur.com/a/z6T6Cv8

**Comment by koerner-axs** [comment]
I have the same problem when training networks from the command line.

**Comment by koerner-axs** [comment]
I believe the problem to lie in the function cellpose.io.get_image_files as you described:

`image_names.extend(glob.glob(folder + f'/*{imf}{ext}'))`
`image_names.extend(glob.glob(folder + f'/*{imf}{ext.upper()}'))`

glob is used here to match potential input files. These two lines of code intend to make this search invariant of the case of the file extension. glob.glob, however already matches case-insensitively. Because we are extending a simple list, this doubles up the input files.

Uncommenting the second line resolves the issue. For forward compatibility reasons, it may be advisable to leave this as is and later on remove duplicates (or put the filenames in a set right away, I guess).

**Comment by zelunw** [comment]
Thanks for opening this issue - I have the same experience.

I also have the issue where, after a round of training in the GUI, it does not advance to the next image in the folder. Instead it opens the same image with computed masks using the new model. Wondering if it's caused by the same issue

**Comment by lacan** [comment]
Yep experiencing this bug too... Looking forward to a patch :)

**Comment by carsen-stringer** [comment]
ahh sorry about this, I've added a line to remove duplicates, please 
```pip install git+https://github.com/mouseland/cellpose.git```
to test it
