### ISSUE TITLE
How can I differentiate between cells of different classes?  i.e. Multiclass instance segmentation

### ISSUE THREAD

**Issue by its-jd** [MouseLand/cellpose#650]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
May be, multichannel mask output, where each channel contains cells of one specific class.

For example, I have one image that contains a few RBCs and WBCs. If I pass this image to Cellpose, it can identify different cells in the image. How can I determine the class of each cell from the Cellpose output(mask)? 

![image](https://user-images.githubusercontent.com/41875270/215425704-55f2c406-7eab-4d87-b757-59d4c63b8668.png)

![image](https://user-images.githubusercontent.com/41875270/215425567-5bfe507f-6a15-49de-8bd5-335b8ba01669.png)

**Comment by carsen-stringer** [comment]
this is not high-priority for us to implement

one workaround for this problem is to train two models -- one with your RBCs labelled and one with your WBCs labelled. then the model should only detect one or the other. another workaround could be to segregate this image based on color before segmentation -- it seems like the WBCs are more in the blue channel than the RBCs? you could run cellpose on the blue channel to get the WBCs specifically.
