### ISSUE TITLE
Single object segmentataion using Cellpose

### ISSUE THREAD

**Issue by maulakhan** [MouseLand/cellpose#670]
Dear cellpose maintainers,

I want to do segmentation of only one object in a 2D image like described here:
https://forum.image.sc/t/single-object-segmentation-using-cellpose/77869

Is it altogether possible or am I doing something wrong?

@carsen-stringer 

Best,
Arif

**Comment by carsen-stringer** [comment]
I think for single masks or a few masks you would need to train the model from scratch, because Cellpose has been trained with images with many objects.

Alternatively an approach like a standard u-net or other filtering and watershed may be appropriate for this. I'd check out Cellprofiler for this, it has many options: https://cellprofiler.org/

**Comment by carsen-stringer** [comment]
also this advice is useful: https://forum.image.sc/t/single-object-segmentation-using-cellpose/77869/2
