### ISSUE TITLE
Cellpose masks saving with darker at the top.

### ISSUE THREAD

**Issue by Utkarsha666** [MouseLand/cellpose#710]
Description
I am new to Cellpose, so this issue may be basic, but I am encountering a peculiar problem. The generated masks are labeled correctly, and everything works smoothly throughout the process. However, when I try to save the masks, an unusual phenomenon occurs. The cells located at the top of the image progressively become darker, while the cells at the bottom appear brighter. At the extreme top, the cells blend entirely with the background, resulting in the loss of those cells. Am I doing something wrong? Please guide me.

**To Reproduce**
1. Go to 'File'
2. Click on 'Save masks as PNG/tif'
3. To see error open the saved masks.

**Comment by mrariden** [comment]
This is expected and intended behavior. The mask file is being saved with each pixel as background (represented by a 0), or as a cell label (represented by the cell label number). The gradient is produced because each cell label is unique and monotonically increasing from top to bottom.  

You can use different look up tables to view the resulting masks or threshold everything above zero to get everything that cellpose detects. Image post processing is outside the scope of cellpose, but you can find additional help at https://forum.image.sc/tag/cellpose. 

I will add this to the FAQ section on the read the docs page.
