### ISSUE TITLE
[FEATURE] Saving single cell NPY files from a batch of multiple cell images

### ISSUE THREAD

**Issue by davalencia0914** [MouseLand/cellpose#761]
Thanks for continuing to add to Cellpose! It's been amazing for me. I've been using Cellpose in the command line for bulk processing of many images and use another program that concerts my .npy files into pickle objects for compatible cell outlines. For some reason adjacent cell outlines on the .npy file merge into a single pickle object. To easily prevent this rather than manually deleting adjacent cell outlines, I was wondering if it's possible to make a bulk processing code that can save a single cell outline from a multi cell .npy file and iterate through each of the Cellpose outlines to save individual single cell .npy files?

**Comment by mrariden** [comment]
Would you be able to use the built in `--save_outlines` feature instead of writing something? It saves the outlines as a png with each outline having that cell's id. IMO that would be easier than working with the .npy files. 

But if you have to work with the .npy file I'm still not sure what the issue with pickling is. You should be able to access unique outlines for each cell using the .npy file. 

The 'outlines' key in the dictionary saved to the .npy file is essentially an image. Pixels that have a cell outline for a given cell id are labeled with that cell's ID. You should be able to iterate through the unique cell id's and find the outline pixels in the numpy file by checking. Something like:
```python
npy_data = np.load("yourfile.npy", allow_picks=True).item()
outlines = npy_data['outlines']
cell_idxs = np.unique(outlines)
for idx in cell_idxs:
    this_outline = np.where(outlines == idx)  # this returns the coords of the outline pixels, check the numpy docs for more info
    # Do something with this_outline
```
Alternatively, you could make a new 2d outline array for each cell outline depending on your needs.

**Comment by davalencia0914** [comment]
Thanks so so much! You just saved me about 200 hours of my PhD. The other program that would pickle the npy files had essentially identical code to yours from the start, but then I think it was a bit "over-engineered" and resulted in merging nearby cell outlines for some odd reason. For future reference to those seeing this, I'm putting the original code that didn't work below from the cellposeEdge function:

def cellposeEdge(npy_file, outputFolder, count, xres, scale):
    mask = np.load(npy_file, allow_pickle=True, fix_imports=True, encoding='bytes').item()
    binary_mask = mask['outlines']
    filled = ndimage.binary_fill_holes(mask['outlines'])
    labels, num_features = ndimage.label(filled)
    objects = np.zeros((labels.shape[0], labels.shape[1], num_features))
    
    for i in range(np.max(labels)):
        print(i)
        mask = (labels == i+1)
        objects[:,:,i] = mask*1
    
    for obj in range(objects.shape[2]):
        print(obj)
        coords = np.where(objects[:,:,obj] > 0)
        coords = np.flip(coords, axis=0)
        x = coords[0] / xres
        y = coords[1] / xres

The corrected version below:
def cellposeEdge(npy_file, outputFolder, count, xres, scale):
    mask = np.load(npy_file, allow_pickle=True, fix_imports=True, encoding='bytes').item()
    binary_mask = mask['outlines']
    cell_idxs = np.unique(binary_mask)
    for idx in cell_idxs:
        outline_coords = np.where(binary_mask == idx)
        # this returns the coords of the outline pixels, check the numpy docs for more info
        print(idx)
        coords = np.flip(outline_coords, axis=0)
        x = coords[0] / xres
        y = coords[1] / xres
