### ISSUE TITLE
[BUG]Percentile normalization when norm3d=True

### ISSUE THREAD

**Issue by derekthirstrup** [MouseLand/cellpose#893]
**Describe the bug**
I wrote a script to denoise tif stacks using the new DenoiseModel class from Cellpose 3.  It works great but there appears to be an issue with the normalization step.  It appears to be performing a per z slice normalization which boost noise in out of focus planes.  I assumed that passing norm3D= True to eval method would perform a per stack normalization of intensities.  However it still appears to be doing per slice.  What is the optimal way to force the normalization to be per stack? I did also evaluate stack normalization outside of cellpose but it seems to degrade the denoising performance and leads to a grainy output for this lamin tagged cell line.  Left image is sequential rescaling subtracting camera offset and rescaling to max px value before passing to DenoiseModel percentile rescaling from [0,99] and right is just camera offset to max px value denoising.  I think the z planes that are in focus look to be higher contrast with the sequential option but suffer from the out of focus planes boosting noise.
![image](https://github.com/MouseLand/cellpose/assets/20077409/3b6d3081-8ff9-4d4c-9c2f-56c6405b02d9)

Here is an out of focus plane example:
![image](https://github.com/MouseLand/cellpose/assets/20077409/fe15dc8b-4472-4a03-8458-694660c806c9)

**Comment by anoshqa** [comment]
Hi, can you share your codes to attempt norm3D=True please? I read the docs where I have to pass a whole dictionary in normalize=True but am struggling. When I import my tif stack into GUI it automatically uses the following - {'lowhigh': None, 'percentile': [1.0, 99.0], 'normalize': True, 'norm3D': True, 'sharpen_radius': 0, 'smooth_radius': 0, 'tile_norm_blocksize': 0, 'tile_norm_smooth3D': 1, 'invert': False}, and then I run denoise and the noise actually gets enhanced (instead of getting removed)

**Comment by carsen-stringer** [comment]
sorry there was a bug in the norm3D step, I think it should be working now, if it's not then I'll reopen the issue
