### ISSUE TITLE
3D segmentation speed

### ISSUE THREAD

**Issue by timblosser** [MouseLand/cellpose#95]
What is the anticipated increase in time going from 2D --> 3D? I have a (7,2048,2048) stack. If I run each z slice separately as 2D it takes about 1 minute to evaluate the model (per 2D image). I'm now trying to evaluate the model in 3D and it's going on 2 hours. I'm wondering if I'm not implementing it correctly or if it's expected to take much longer.

**Comment by chrisroat** [comment]
I've noticed this same increase in "shallow z" images.  In your case, it is doing 2048 7x2048 evaluations twice (once for yz and once for xz), whereas there are only 7 xy evaluations.  I was curious if these shallow/narrow evaluations could be batched together and make things faster in #83, and the authors response on that issue seems to indicate it might be possible.

**Comment by chrisroat** [comment]
I also suspect that shallow z 3d images may not work well.  The internal batch size is set to 224, so in the xz and yz evaluations, I think the z direction is padded to 224 (with 217 rows of zeros).  I suspect the flow computation by the neural network in such cases might be suboptimal, but hopefully the authors will let us know.  I also don't know if there is anisotropy in the pixel resolution if things will be optimal.

**Comment by carsen-stringer** [comment]
I've modified the `_run_tiled` function so that these small images (which create only 1 tile in one axis if `augment=False`) will be stacked together in a single batch

**Comment by carsen-stringer** [comment]
also there is an `anisotropy` parameter available to try

**Comment by carsen-stringer** [comment]
also @timblosser to reduce run time set both `augment=False` and `net_avg=False`. apologies for the delay on this
