### ISSUE TITLE
Guidance on optimal sizes

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/cellpose#97]
I have large 200k x 8k x 8k images that I'm breaking up into chunks to run 3d evaluation in parallel on multiple GPUs.  I believe that I'm seeing edge effects (for cells close to chunk boundaries), so I am including data from neighboring chunks for each chunk.   I see that a tiling is done of size 224x224.  

What are optimal chunk sizes and overlap regions in order to minimize these effects?  Would a 112 overlap be enough?

**Comment by marius10p** [comment]
What is your ROI size in X,Y,Z ? I would use about twice that. You will then have to merge ROIs that are detected multiple times, for example if they have substantial pixel overlap.

**Comment by chrisroat** [comment]
I appreciate your response!

The ROI is dozens of pixels.  It helps to know it's the ROI scale that matters.  I was concerned that the tile size might play a role.  And yes, I do merge the ROIs.

I note that the tile size of 224 is an internal parameter and not directly exposed.   Given that its the ROI scale that is important, do you have any advice for/against changing the tile size?

**Comment by marius10p** [comment]
The pipeline internally resizes all images to a common cell size (I think it's about 27 pixels diameter). 224 is a good size to get good speedups. The tile overlap for augmentation is different, there we want to have 4-fold overlap as a test-time augmentation strategy,

**Comment by chrisroat** [comment]
Is the performance tuned to a size of 224?   Would detrimental result we expected for using sizes other than 224?  (I'm not at all worried about computational performance here -- just the algorithm's results.). My goal would be to use factors of 2, since a lot of my up and down-stream processing is less congested that way.  At minimum, I'd like to go with chunks of 256.

My smaller images are 200x8000x8000, which are broken into chunks for parallel processing (with padding to avoid edge effects, and allowance to join cells that cross chunk boundaries)

**Comment by chrisroat** [comment]
@marius10p It looks like the default diameters parameter is 27, and the diam_mean is 30.  Does this mean a 10% rescaling is always done if default parameters are used?

In my opinion, the code seems to be trying to do a *lot* -- there are a lot of if/then/else stanzas, some of which depend on each other across different pieces of the code.  It gets difficult to follow.  For example, I tried to work around the [tiling issue](https://github.com/MouseLand/cellpose/issues/98) by subdividing my image with custom sizes, but now realize part of my delicate chunking is overridden by the rescaling.

I would like to control the rescaling of the image myself, so that I can chunk exactly how I want.  Will it suffice to turn off the rescaling when doing 3d images by setting diameter to 27?  I believe so in reading the code, but am not sure if there is some code path I'm missing.

**Comment by marius10p** [comment]
I agree, we're going to have to do a refactor at some point. All that tiling and augmentation makes  a difference in accuracy, hence why it's so tightly built into the code. Performance on each of our internal tiles is tuned to a size of 224 from the training set, but it doesn't matter what the image is since we always tile and augment it,. I would recommend not to worry about all that and choose the chunk size based on intuitive principles: is there enough context in the tiles that most cells can be easily segmented? 

I'll have to look at the 27 vs 30 for diameters. Rescaling within +/- 30% won't make much of a difference, but it would be good to keep it consistent!

**Comment by chrisroat** [comment]
I'm happy to leave the internal tiles at 224, if that has been what is optimized for.

As far as chunks, I do need to the number of x/y tiles = 2 mod 4 in a chunk (after padding so I can join neighboring chunks), if I want to get the full benefit from the tiling.  Otherwise, the 4 orientations of a given region will have duplication (in the current implementation).  The curveball was that if I have objects with diameter=13.5, the image was being doubled in size internally and throwing off that calculation.

**Comment by carsen-stringer** [comment]
sorry if there were inconsistencies in this, it is now set to 30 everywhere. The model was trained with a diameter of 30 (but it was called 27 because of the way we compute the diameter as the square root of the number of pixels, which is now scaled by `2/np.pi**0.5` to be the diameter of a circle instead of a square. A diameter of 30 in the cyto model will result in no scaling and a diameter of 17 in the nuclei model will result in no scaling.
