### ISSUE TITLE
[BUG] train_labels_files not passed to _process_train_test() in `cellpose.train`

### ISSUE THREAD

**Issue by delnatan** [MouseLand/cellpose#989]
**Describe the bug**
I was trying to train cellpose in a Jupyter notebook using `train.train_seg()` using a list of filenames rather than list of images. When passing a list of labels filenames to the `train_labels_files` to train_seg(), I got an error saying that the list of labels files is empty for the labels. 

In the [source code](https://github.com/MouseLand/cellpose/blob/0ab64c72e20f5e9f4fe232b929cc9b228c5af358/cellpose/train.py#L384), train_labels_files arguments is not used but later assigned via 'un-splatting' `out` to a variable with the name train_labels_files.

Is train_seg() function not intended to use a list of labels filenames for the argument train_labels_files?

Thanks!

**Comment by mpesavento** [comment]
I'm running into this issue as well. I'm passing in `train_labels_files` to `train.train_seg()` and getting an index error when `_process_train_test()` tries to load the data, because `train_labels_files==[]`. 

My current workaround is to change my data directory structure to only have the files I want to train on, which is impractical in the long run.

**Comment by carsen-stringer** [comment]
sorry this is fixed now
